In [1]:
from pathlib import Path
from utils import QmdlLogsHelper
import numpy as np

In [2]:
path_project = '/disk/sean/5glogs'
path_rawlogs = Path(path_project) / Path('sa_ho_event.qmdl')
logs_helper = QmdlLogsHelper(path_rawlogs)

In [17]:
data = logs_helper.get_dataset_ho()
print(data, data.shape)

[[282404 282504      1]
 [505972 506072      1]
 [522872 522972      1]
 [736911 737011      1]
 [882025 882125      1]
 [ 39900  40000      0]
 [ 79900  80000      0]
 [119900 120000      0]
 [159900 160000      0]
 [199900 200000      0]] (10, 3)


In [15]:
len(max(logs_helper.logs_list, key=len)) # 5402
max([len(l) for l in logs_helper.logs_list]) # 5402

5402

In [16]:
np.vstack([[[1], [2]], [[3],[4]]])

array([[1],
       [2],
       [3],
       [4]])

In [4]:
# len(logs_helper.logs_list) # 979805 = 269 + 979536
# sum([1 if log[0:1] == b'\x60' else 0 for log in logs_helper.logs_list[:]]) # 269
# print(b'\x60') # b'`'

In [36]:
modem_event_logs = [log for log in logs_helper.logs_list if log[0:1] == b'\x60']
non_modem_event_logs = [log for log in logs_helper.logs_list if log[0:1] != b'\x60']
# len(modem_event_logs) # 269
# len(non_modem_event_logs) # 979536
# modem_event_logs[0][:10] # b'`\x84\x90}\xefr\xde\x89\xefs'
# non_modem_event_logs[0][:10] # b'\x00\x00\x00\x00\x00\x0e\x00\x00\x00\x00'

In [42]:
modem_event_logs_length_list = [len(l) for l in modem_event_logs]
# max(modem_event_logs_length_list) # 1708
print(modem_event_logs_length_list)

[108, 1, 49, 39, 40, 103, 260, 48, 19, 1113, 20, 36, 12, 29, 1, 51, 19, 73, 1, 19, 67, 19, 39, 60, 1, 100, 8, 15, 13, 34, 18, 54, 68, 43, 9, 123, 41, 4, 4, 63, 19, 36, 20, 19, 39, 74, 24, 33, 39, 27, 28, 110, 24, 19, 38, 19, 30, 128, 1, 53, 19, 252, 39, 5, 88, 9, 226, 1, 19, 29, 9, 39, 15, 39, 53, 67, 4, 4, 24, 74, 471, 19, 19, 44, 73, 53, 69, 4, 60, 106, 4, 53, 44, 14, 9, 59, 54, 4, 53, 14, 88, 42, 315, 63, 19, 29, 19, 251, 279, 63, 19, 14, 7, 345, 44, 44, 39, 17, 142, 24, 53, 118, 58, 1655, 1655, 1655, 1655, 163, 53, 19, 116, 3, 34, 24, 19, 56, 177, 146, 244, 24, 19, 64, 53, 86, 83, 19, 873, 19, 39, 310, 4, 1, 19, 192, 19, 72, 9, 74, 39, 19, 217, 64, 32, 12, 44, 12, 40, 4, 20, 19, 88, 34, 1, 9, 69, 49, 385, 123, 29, 39, 54, 14, 21, 63, 60, 53, 547, 14, 47, 19, 39, 53, 28, 60, 188, 9, 33, 32, 127, 32, 127, 32, 43, 32, 43, 32, 43, 32, 19, 150, 18, 1245, 1245, 882, 13, 13, 25, 13, 25, 20, 43, 373, 19, 61, 9, 9, 69, 14, 1, 824, 53, 24, 53, 126, 103, 3, 4, 1, 153, 19, 24, 43, 9, 19, 9, 14

In [40]:
non_modem_event_logs_length_list = [len(l) for l in non_modem_event_logs]
max(non_modem_event_logs_length_list)

5402

In [97]:
a = b'\x74'
b = b'\xFF'
assert a[0] == a[0] & b[0] # 116
assert a == bytes([a[0] & b[0]]) # b't'
assert b'\x0f'[0] == 15

In [99]:
# hangover start logs
for i, log in enumerate(modem_event_logs):
    if (a := b'\x74') in log:
        idx = log.index(a)
        if idx + 1 < len(log):
            nxt = log[idx + 1] & b'\x0f'[0]
            if nxt == b'\x0c'[0]:
                print(i, idx, nxt)

64 54 12
118 98 12
127 4 12
196 23 12
238 29 12


In [16]:
ho_start_ids = [64, 118, 127, 196, 238]
ho_start_logs = [modem_event_logs[i] for i in ho_start_ids]
[len(l) for l in ho_start_logs]

[88, 142, 163, 33, 153]

In [98]:
# hangover success
for i, log in enumerate(modem_event_logs):
    if (a := b'\x76') in log:
        idx = log.index(a)
        if idx + 1 < len(log):
            nxt = log[idx + 1] & b'\x0f'[0]
            if nxt == b'\x0c'[0]:
                print(i, idx, nxt)

108 269 12


In [18]:
modem_event_logs = {i:log for i, log in enumerate(logs_helper.logs_list) if log[0:1] == b'\x60'}
keys = list(modem_event_logs.keys()); print(len(keys))
k0 = keys[0]
diff = [(k1, k2, k2 - k1) for k1, k2 in zip(keys, keys[1:])]
diff_less100 = [(k1, k2, d) for k1, k2, d in diff if d < 100]; print(len(diff_less100))
diff_less100

269
32


[(41642, 41644, 2),
 (41644, 41646, 2),
 (181842, 181844, 2),
 (498814, 498822, 8),
 (530414, 530449, 35),
 (536651, 536659, 8),
 (548218, 548220, 2),
 (615687, 615689, 2),
 (647405, 647407, 2),
 (647407, 647409, 2),
 (647409, 647411, 2),
 (647411, 647414, 3),
 (647414, 647417, 3),
 (647417, 647419, 2),
 (721319, 721321, 2),
 (738886, 738900, 14),
 (738900, 738901, 1),
 (738901, 738941, 40),
 (738941, 738942, 1),
 (739852, 739854, 2),
 (739854, 739872, 18),
 (739872, 739874, 2),
 (739874, 739925, 51),
 (739925, 739927, 2),
 (763495, 763498, 3),
 (763498, 763517, 19),
 (764343, 764396, 53),
 (766306, 766307, 1),
 (868662, 868670, 8),
 (882125, 882145, 20),
 (933570, 933634, 64),
 (935500, 935576, 76)]

In [32]:
# hangover start logs
ho_start_logs = {}
for k in modem_event_logs.keys():
    if (a := b'\x74') in (log := logs_helper.logs_list[k]):
        id1 = log.index(a)
        if (id2 := id1 + 1) < len(log):
            nxt = log[id2] & b'\x0f'[0]
            if nxt == b'\x0c'[0]:
                print(k, id1, nxt)
                ho_start_logs[k] = log
print(ho_start_logs.keys())

282504 54 12
506072 98 12
522972 4 12
737011 23 12
882125 29 12
dict_keys([282504, 506072, 522972, 737011, 882125])


In [56]:
positive_ids = []
for k in ho_start_logs.keys():
    positive_ids.append([i for i in range(k-100, k)])
for ids in positive_ids:
    print(f'{ids[0]}, {ids[1]}, {ids[2]}, ..., {ids[-2]}, {ids[-1]}')

282404, 282405, 282406, ..., 282502, 282503
505972, 505973, 505974, ..., 506070, 506071
522872, 522873, 522874, ..., 522970, 522971
736911, 736912, 736913, ..., 737009, 737010
882025, 882026, 882027, ..., 882123, 882124


In [69]:
for ids in positive_ids:
    print(max([len(logs_helper.logs_list[i]) for i in ids]))

1162
2073
1156
1322
1750


In [63]:
neg_start, neg_delta = 40000, 40000
negative_logs_keys = [k for k in range(neg_start, neg_start + 5 * neg_delta, neg_delta)]
negative_ids = []
for k in negative_logs_keys:
    negative_ids.append([i for i in range(k-100, k)])
for ids in negative_ids:
    print(f'{ids[0]}, {ids[1]}, {ids[2]}, ..., {ids[-2]}, {ids[-1]}')

39900, 39901, 39902, ..., 39998, 39999
79900, 79901, 79902, ..., 79998, 79999
119900, 119901, 119902, ..., 119998, 119999
159900, 159901, 159902, ..., 159998, 159999
199900, 199901, 199902, ..., 199998, 199999


In [68]:
for ids in negative_ids:
    print(max([len(logs_helper.logs_list[i]) for i in ids]))

1114
1738
1626
234
2743
